server:
  port: 9191

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: movie-catalog-service
          uri: lb://movie-catalog-service
          predicates:
            - Path=/catalog/**
#          filters:
#            - name: Hystrix
#              args:
#               name: fallbackcmd
#                fallbackuri: forward:/moviecatalogFallBack
    config:
      enabled: true
      uri: http://localhost:8888


eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream




#Needed for kubernetes. Not configured here. Configured in kubernetes resource files.
#eureka:
#  instance:
#    preferIpAddress: true
#    hostname: eureka-0
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
