spring:
  application:
    name: ratings-data-service
  cloud:
    config:
      uri: http://localhost:8888


server:
  port: 8083



eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/





#Needed for kubernetes. Not configured here. Configured in kubernetes resource files.
#eureka:
#  instance:
#    preferIpAddress: true
#    hostname: eureka-0
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
