server:
  port: 8081

management.endpoints.web.exposure.include: hystrix.stream


spring:
  application:
    name: movie-catalog-service
  cloud:
    config:
      uri: http://localhost:8888


eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      default-zone: http://localhost:8761/eureka/




#Needed for kubernetes. Not configured here. Configured in kubernetes resource files.
#eureka:
#  instance:
#    preferIpAddress: true
#    hostname: eureka-0
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
