apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-gateway-app
  template:
    metadata:
      labels:
        app: cloud-gateway-app
    spec:
      containers:
      - name: cloud-gateway-app
        image: shaswata79/microservice-demo-v2:api-gateway
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        imagePullPolicy: Always
        ports:
          - containerPort: 9191
        env:
          - name: EUREKA_INSTANCE_PREFER-IP-ADDRESS
            value: 'true'
          - name: EUREKA_INSTANCE_HOSTNAME
            value: eureka-0
          - name : EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE
            value: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka


---

apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway-svc
spec:
  type: LoadBalancer
  selector:
    app: cloud-gateway-app
  ports:
  - port: 80
    targetPort: 9191
    protocol: TCP

