apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-configmap
data:
  eureka-service-address: http://eureka-0.eureka:8761/eureka

---
#Headless service

apiVersion: v1
kind: Service     
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  clusterIP: None      #indicates headless service
  ports:
    - port: 8761
      name: eureka
  selector:
    app: eureka


---


apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
spec:
  serviceName: "eureka"     #name of the headless service
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: shaswata79/microservice-demo:discovery-server-api
        imagePullPolicy: Always
        ports:
        - containerPort: 8761
        env:
          - name: EUREKA_SERVER_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: eureka-configmap
                key: eureka-service-address
        


---

#service to connect to the stateful set

apiVersion: v1
kind: Service
metadata:
  name: eureka-lb
  labels:
    app: eureka
spec:
  selector:
    app: eureka
  type: NodePort
  ports:
  - port: 80
    targetPort: 8761




