apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-info-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-info-app
  template:
    metadata:
      labels:
        app: movie-info-app
    spec:
      containers:
      - name: movie-info-app
        image: shaswata79/microservice-demo:movie-info-api
        ports:
        - containerPort: 8082


---


apiVersion: v1
kind: Service
metadata:
  name: movie-info-svc
spec:
  type: LoadBalancer
  selector:
    app: movie-info-app
  ports:
  - port: 80
    targetPort: 8082

