apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-catalog-app
  labels:
    app: movie-catalog-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-catalog-app
  template:
    metadata:
      labels:
        app: movie-catalog-app
    spec:
      containers:
      - name: movie-catalog-app
        image: shaswata79/microservice-demo:movie-catalog
        imagePullPolicy: Always
        ports:
        - containerPort: 8081


---


apiVersion: v1
kind: Service
metadata:
  name: movie-catalog-svc
spec:
  type: ClusterIP
  selector:
    app: movie-catalog-app
  ports:
  - port: 80
    targetPort: 8081





