apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-data-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings-data-app
  template:
    metadata:
      labels:
        app: ratings-data-app
    spec:
      containers:
      - name: ratings-data-app
        image: shaswata79/microservice-demo-v2:ratings-data-api
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8083
        env:
          - name: EUREKA_INSTANCE_PREFER-IP-ADDRESS
            value: 'true'
          - name: EUREKA_INSTANCE_HOSTNAME
            value: eureka-0
          - name : EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE
            value: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka


---


apiVersion: v1
kind: Service
metadata:
  name: ratings-data-svc
spec:
  type: ClusterIP
  selector:
    app: ratingd-data-app
  ports:
  - port: 80
    targetPort: 8083
