apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-data-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings-data-app
  template:
    metadata:
      labels:
        app: ratings-data-app
    spec:
      containers:
      - name: ratings-data-app
        image: shaswata79/microservice-demo:ratings-data-api
        ports:
        - containerPort: 8083


---


apiVersion: v1
kind: Service
metadata:
  name: ratings-data-svc
spec:
  type: ClusterIP
  selector:
    app: ratingd-data-app
  ports:
  - port: 80
    targetPort: 8083
